AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base network infrastructure for userCreator-iam-role'

Parameters:
  GithubAccount:
    Type: String
  GithubRepository:
    Type: String
  AssumeRoleName:
    Type: String

Resources:
  GithubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AssumeRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:sub':
                  - !Sub 'repo:${GithubAccount}/${GithubRepository}:ref:refs/heads/main'
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      #   ManagedPolicyArns:
      #     - arn:aws:iam::aws:policy/AWSAmplifyAdminAccess
      Policies:
        - PolicyName: AmplifyDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - amplify:CreateApp
                  - amplify:DeleteApp
                  - amplify:UpdateApp
                  - amplify:ListApps
                  - amplify:StartDeployment
                  - amplify:StopDeployment
                  - amplify:CreateBranch
                  - amplify:DeleteBranch
                  - amplify:UpdateBranch
                  - amplify:ListBranches
                  - amplify:CreateWebhook
                  - amplify:DeleteWebhook
                  - amplify:UpdateWebhook
                  - amplify:ListWebhooks
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::amplify-*'
      Tags:
        - Key: Project
          Value: UserCreator
