import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from './component/Header'
import { SessionProvider } from 'next-auth/react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`h-lvh ${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}
      >
        <SessionProvider>
          <div className="">
            <Header />
          </div>
          <div className="h-full">{children}</div>
        </SessionProvider>
      </body>
    </html>
  )
}
