name: Deploy to Amplify

on:
  push:
    branches:
      - main # デプロイをトリガーするブランチを指定

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Change directory to amplify-next-test
        run: cd amplify-next-test

      - name: Initialize Amplify
        run: |
          amplify init --yes \
            --amplify "{\"envName\":\"${{ vars.AMPLIFY_ENV_NAME }}\"}" \
            --providers "{\"awscloudformation\":{\"Region\":\"${{ vars.AWS_REGION }}\"}}" \
            --categories "{}"

      - name: Publish to Amplify
        run: amplify publish --yes
